version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONASYNCIODEBUG=1
    depends_on:
      - minio
    networks:
      - meme_network

  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio_data:/data
    networks:
      - meme_network

volumes:
  minio_data:

networks:
  meme_network:
    driver: bridge
